### PR TITLE
catkinizing apriltags_cpp as a third-party package

### PR DESCRIPTION
**Pull request by ayrton04**
@locusrobotics/robot-software-team

### CODE REVIEW

**Comment by tappan-at-git** [comment]
LGTM if this builds as expected.

**Comment by ayrton04** [comment]
Need to hold off. It builds fine, but I need to export the flags required for anything else that needs it.

**Comment by ayrton04** [comment]
OK, this is ready again. Note that despite the directory name, I called the package apriltags_cpp, as the hyphen is not a valid package name for catkin, and causes it to complain. It will still build, however, so if anyone dislikes this strongly enough, I can change it.

**Comment by ayrton04** [comment]
Update: I just renamed the repo so everything can be consistent. It doesn't break anything.

**Comment by ayrton04** [comment]
Since this is just build stuff and it's holding up other work, merging.

**Pull request merged**
