### PR TITLE
Adding libopencv-dev dependency

### PR DESCRIPTION
**Pull request by ayrton04**
Addresses #4.

@locusrobotics/robot-software-team

### CODE REVIEW

**Comment by tappan-at-git** [comment]
LGTM. What's the issue with depending on the ROS package?

**Comment by ayrton04** [comment]
This isn't a ROS package, so depending on a ROS package adds all sorts of dependencies we don't want.

**Comment by tappan-at-git** [comment]
:+1:

**Comment by ayrton04** [comment]
This issue is blocking release of this package, so merging.

**Pull request merged**
